# Welcome {.unnumbered}

This is a book by the [Biological and Environmental Data Education (BEDE) Network](https://qubeshub.org/community/groups/bede/about). It was written to support the many biology and environmental science instructors who teach programming but never received formal instruction themselves. Though the computer science pedagogy literature contains many evidence-based teaching techniques, the jargon and examples are rarely relevant to biology and environmental science contexts. Each chapter of this book distills one such technique using biology-friendly language and demonstrates how to apply the technique in lectures, labs, and/or assessments. We were inspired by James M. Lang's *Small Teaching* [@lang21], which encourages incremental improvements to instruction. Biology and environmental science instructors don't need to become computer science pedagogy experts overnight. Rather, our intention is to provide digestible resources for instructors to gradually improve the quality of their programming teaching.
